### PR TITLE
Regenerate proto files using the latest grpc version (dd828651e452295…

### PR DESCRIPTION
**Pull request by sjezewski**
…41896bc41cd9cf2f89ac7002a) which has breaking changes to '_API_GetVersion_Handler'

Oh how annoying ... GH broke the commit hash in the title. The latest grpc hash is:

dd828651e45229541896bc41cd9cf2f89ac7002a

All I did was 'make proto'

For some reason, I seemed to need to use sudo ... since I got the following error:

```shell
$chown /var/folders/xb/wnfvvcr56cb7px04w56k1jt40000gn/T/protoeasy-input343963475/http: operation not permitted
```

... without it.

### CODE REVIEW

**Comment by peter-edge** [comment]
Do it within docker? Also make proto doesn't look like it fully ran as there are now package comments added

**Comment by sjezewski** [comment]
Hmmm ... do you have an image preference / an image you usually use to compile proto files?

We just went through docker-izing our proto build process and the assumptions/versions/dependencies for all of that. So, I'm happy to run it if you have a specific image in mind, but if you don't, then perhaps its easier for you to run?

Unless you just use a basic ubuntu image or something.

**Comment by peter-edge** [comment]
Ya, the image that is provided with protoeasy, as described in the
protoeasy readme

**Comment by peter-edge** [comment]
I did this myself, closing

**Pull request closed without merging**
